server:
  port: 8092
spring:
  r2dbc:
    url: r2dbc:h2:mem:///userdb
    #username: username
    #password: password
    #url: r2dbc:postgresql://localhost:5432/userdb
    #username: user
    #password: admin
